name: "Test"
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        perl:
          - "5.44"
          - "5.42"
          - "5.40"
          - "5.38"
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
        redis:
          - "8.10"
          - "8.8"
          - "8.6"
          - "8.4"
          - "8.2"
          - "8.0"
          - "7.4"
          - "7.2"
          - "6.2"
        include:
          - os: "macos-latest"
            perl: "5.44"
            redis: "8.10"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@ac3202722f5744e62a8fa3af3e1aaaebb08861f3 # v1.44.0
        with:
          perl-version: ${{ matrix.perl }}

      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@ffaf3c39499b2917543d84f6acc818277580b531 # v1.58.1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: false

      - name: Install
        run: cpanm --quiet --installdeps --notest .
      - run: perl Build.PL
      - run: prove -lv t

  author:
    name: author test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Perl 5
        uses: shogo82148/actions-setup-perl@ac3202722f5744e62a8fa3af3e1aaaebb08861f3 # v1.44.0
        with:
          perl-version: "5"
      - name: Install
        run: |
          cpanm --quiet --with-develop --installdeps --notest .
          cpanm --quiet Test::Perl::Critic
      - run: perl Build.PL
      - run: prove -lv xt
