name: "Update commands"
on:
  schedule:
    - cron: "0 0 * * 1" # every Monday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # for shogo82148/actions-github-app-token
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@ac3202722f5744e62a8fa3af3e1aaaebb08861f3 # v1.44.0
        with:
          perl-version: "5"

      - name: Install
        run: cpanm --quiet --installdeps --notest .

      - name: Download commands.json
        run: curl -sSfL -o "$RUNNER_TEMP/commands.json" https://raw.githubusercontent.com/redis/docs/refs/heads/main/data/commands.json

      - name: Generate
        run: perl author/generate_commands.pl "$RUNNER_TEMP/commands.json"

      - name: Test
        run: prove -l t/00_compile.t t/12_filters.t

      - name: Generate token
        id: generate_token
        uses: shogo82148/actions-github-app-token@23fb7b487bbb34ec0de312a6bb579dd98e217a45 # v1.3.2

      - name: Commit and create a pull request
        uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          head-branch-prefix: "auto-update-commands/"
          commit-message: "update the generated commands"
          title: "Update the generated commands"
          body: |
            This pull request is created by the "Update commands" workflow.
            It regenerates the methods of Redis commands from https://raw.githubusercontent.com/redis/docs/refs/heads/main/data/commands.json.
